version: "2"

volumes:
  redis-db:
  tailscale:
  tailscale-certs:
  nf-var:
  edo-db:
  edo-logs:
  edo-work:

services:
  redis:
    image: normalframework.azurecr.io/normalframework/redis:2.1
    networks:
      - internal
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data

  nf:
    image: normalframework.azurecr.io/normalframework/nf-full:2.1.4-2
    network_mode: host
    environment:
      - PORT=80
    cap_add:
      - NET_BIND_SERVICE
    depends_on:
      - redis
    volumes:
      -  nf-var:/var
    dns:
      - 100.100.100.100

  edo-service:
    image: mcktechsolutions.azurecr.io/devicecontrol:latest
    networks:
      - internal
    environment:
      - NORMAL_HOST=http://localhost:80
      - REDIS_HOST=redis
    depends_on:
      - nf
      - redis
    volumes:
      - "edo-db:/.db"
      - "edo-logs:/logs"
      - "edo-work:/work"
    dns:
      - 100.100.100.100

  promtail:
    image: mcktechsolutions.azurecr.io/devicepromtail:latest
    environment:
      - DEVICE_ID=Unassigned
    volumes:
      - edo-logs:/var/log/apps/edo-service
    networks:
      - internal

  tailscale:
    image: tailscale/tailscale:v1.46
    network_mode: host
    command: tailscaled
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - "tailscale:/var/lib"
      - "tailscale-certs:/tailscale-certs"
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  internal: